In [1]:
pip install numpy

In [5]:
import numpy as np

In [9]:
print(np.__version__)

1.26.4


In [11]:
#Creating arrays

In [ ]:
#one dimensional array

In [13]:
list1 = [1,2,3]

In [19]:
print(list1)

[1, 2, 3]


In [23]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [27]:
#two dimensional array

In [29]:
list1 = [1,2,3]
list2 = [4,5,6]
arr_list_2 = np.array([list1, list2])
print(arr_list_2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#three dimensional array

In [37]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list_3 = np.array([[list1, list2, list3]])
print(arr_list_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [41]:
print(arr_list_3.ndim)

3


In [43]:
print(arr_list_2.ndim)

2


In [45]:
#numpy array attributes

In [49]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [53]:
print("shape", arr1.shape)
print("Size", arr1.size)
print("dType", arr1.dtype)
print("n_dim", arr1.ndim)

shape (2, 3)
Size 6
dType int32
n_dim 2


In [55]:
# Create 2 array- 1D and 3D, find it's attributes.

In [57]:
arr4 = np.array([1,2,3])
print(arr4)

[1 2 3]


In [59]:
arr5 = np.array([[[4,5,6]]])
print(arr5)

[[[4 5 6]]]


In [61]:
print("shape", arr4.shape)
print("Size", arr4.size)
print("dType", arr4.dtype)
print("n_dim", arr4.ndim)

shape (3,)
Size 3
dType int32
n_dim 1


In [63]:
print("shape", arr5.shape)
print("Size", arr5.size)
print("dType", arr5.dtype)
print("n_dim", arr5.ndim)

shape (1, 1, 3)
Size 3
dType int32
n_dim 3


In [65]:
#Zero array

In [67]:
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [69]:
#One array

In [75]:
ones_arr = np.ones((2,9))
print(ones_arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [77]:
#Full array

In [81]:
full_arr = np.full((3,4), 99)
print(full_arr)

[[99 99 99 99]
 [99 99 99 99]
 [99 99 99 99]]


In [83]:
#Identity Matrix

In [85]:
id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [87]:
#Empty array

In [89]:
print(np.empty(3))

[1. 1. 1.]


In [91]:
#Evenly spaced array

In [97]:
print(np.arange(1,10,2))   #adds one value after one like 1+2 = 3+2= 5 5+2 = 7

[1 3 5 7 9]


In [103]:
#Specific number of values between range     -  1 to 10 is divided into 5 equally spaced

In [105]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [107]:
print(np.linspace(1,10,2))

[ 1. 10.]


In [109]:
#random values array

In [113]:
r_arr = np.random.rand(3,2)  #float form
print(r_arr)

[[0.70296792 0.24039807]
 [0.47243573 0.16681334]
 [0.4721682  0.51615927]]


In [116]:
#random values  array - int

In [118]:
rint_arr = np.random.randint(1,10,(3,3))
print(rint_arr)

[[9 1 8]
 [9 9 3]
 [8 6 5]]


In [120]:
rint_arr = np.random.randint(1,100,(3,3))
print(rint_arr)

[[53 46 83]
 [79 78 53]
 [ 3 50 54]]


In [122]:
#Array Indexing and Slicing

In [130]:
a = np.array([101,3,4,5,6])

In [132]:
print(a)

[101   3   4   5   6]


In [138]:
print(a[0])   ##To check index

101


In [140]:
print(a[2])

4


In [142]:
print(a[-2])

5


In [144]:
#Slicing

In [162]:
b = np.array([1,3,9,7,1])
print(b)

[1 3 9 7 1]


In [156]:
#array[start:stop:step] 
# stop - index, that is not included in output

In [164]:
b[0:4]

array([1, 3, 9, 7])

In [168]:
b[0:2]  #first two elements

array([1, 3])

In [171]:
#to print last element

In [173]:
print(b[-3:])

[9 7 1]


In [175]:
#middle elements finding

In [177]:
print(b[1:3])

[3 9]


In [179]:
print(b[0:3:2])

[1 9]


In [181]:
arr2 = np.array([[1,3,4], [5,6,7]])

In [183]:
print(arr2)

[[1 3 4]
 [5 6 7]]


In [187]:
print(arr2[1][0])

5


In [189]:
 print(arr2[1])
print(arr2[1:])

[5 6 7]
[[5 6 7]]


In [191]:
print(arr2[1:])

[[5 6 7]]


In [193]:
print(arr2[0:])

[[1 3 4]
 [5 6 7]]


In [197]:
print(arr2[:, 0])   #rows:column in 2-D arrays

[1 5]


In [202]:
# [layers/height,rows,columns]

In [204]:
arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [206]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [210]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [216]:
print(arr3[0][2])
print(arr3[2][2])

3
9


In [218]:
#Slicing

In [224]:
print(arr3[:, 0])  #first column value
print(arr3[:, 2])   #second column value

[1 4 7]
[3 6 9]


In [227]:
print(arr3[::2, 0])

[1 7]


In [231]:
print(arr3[::, 1:2]) #slicing on colums
print(arr3[2::, 1:2])  #slicing on rows and columns

[[2]
 [5]
 [8]]
[[8]]


In [233]:
#Array Reshaping and Flattening

In [255]:
arr1 = np.array([1,2,3,4,5,6])

In [257]:
arr1

array([1, 2, 3, 4, 5, 6])

In [263]:
reshaped = arr1.reshape((6,1))

In [265]:
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [269]:
reshaped = arr1.reshape((2,3))

In [273]:
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [279]:
print(reshaped.flatten())

[1 2 3 4 5 6]


In [281]:
#Array Stacking amd Splitting

In [285]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [291]:
print(np.vstack((a,b)))     #Vertical Stacking - row wise
print(np.hstack((a,b)))     #Horizontal Stacking - column wise

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [293]:
#Splitting

In [295]:
c = np.array([[1,2,3], [4,5,6]])

In [297]:
print(c)

[[1 2 3]
 [4 5 6]]


In [305]:
split = np.hsplit(c,3)  #horizontal Split

for s in split:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [307]:
#vertical split

In [311]:
vsplit = np.vsplit(c,2)

for s in vsplit:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [315]:
#Mathematical Operations on array

In [317]:
a = np.array([10,20,30])

In [319]:
print(a)

[10 20 30]


In [321]:
print(a+10)
print(a-10)
print(a/10)
print(a*10)
print(a%10)

[20 30 40]
[ 0 10 20]
[1. 2. 3.]
[100 200 300]
[0 0 0]


In [323]:
b = np.array([1,4,9])
print(b)

[1 4 9]


In [325]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


In [327]:
# To Check sin0, cos0, tan0

In [329]:
#Mathematical Operations on array

In [331]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [333]:
print(np.add(a,b))

[5 7 9]


In [335]:
print(np.multiply(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [337]:
#Dot product

In [339]:
print(np.dot(a,b))

32


In [341]:
print(a.T)  #Transpose

[1 2 3]


In [345]:
t = np.array([[1,2,3],
              [5,6,7]])
print(t)
print(t.T)

[[1 2 3]
 [5 6 7]]
[[1 5]
 [2 6]
 [3 7]]


In [347]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [349]:
print(np.sum(a))

21


In [351]:
print(np.mean(a))

3.5


In [353]:
print(np.median(a))

3.5


In [355]:
print(np.std(a))

1.707825127659933


In [357]:
print(np.min(a))

1


In [359]:
print(np.max(a))

6


In [363]:
# 10 Array  comparision

In [367]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)
#Comparing each elements
print(a == b)
#Comparing Complete array
print(np.array_equal(a,b))

[1 2 3]
[4 5 6]
[False False False]
False


In [371]:
##Broadcasting 
#Broadcasting is a mechanism that allows arithmetic operations to be performed on arrays of different shapes and sizes,
#it eliminates the need for explicit loops or reshaping operations, making code more concise, readable and efficient.

In [375]:
a = np.array([1,2,3,4])
b = np.array([5])
print(a+b)

[6 7 8 9]


In [377]:
c = np.array([[1,2,3], [4,5,6]])
d = np.array([10,20,30])
print(c+d)

[[11 22 33]
 [14 25 36]]


In [379]:
#Handling with null values

In [383]:
data1 = np.array([1,2, np.nan, 4, np.inf])
print(data1)


[ 1.  2. nan  4. inf]


In [385]:
print(np.isnan(data1))

[False False  True False False]


In [387]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [389]:
arr = np.array([1,0,0,8])
print(arr)
np.save('my_array.npy', arr)

[1 0 0 8]


In [397]:
loaded_arr = np.load('my_array.npy')
print(loaded_arr)

[1 0 0 8]
